use_frameworks!

target 'MLKit_Example' do
  pod 'MachineLearningKit', :path => '../'
  pod 'Upsurge'
  
  target 'MLKit_Tests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '4.0'
          end
      end
  end
  
end


